; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

[env:tugas1]
build_src_filter = +<tugas1.cpp> -<tugas2.cpp> -<tugas3.cpp> -<tugas4.cpp>

[env:tugas2]
build_src_filter = +<tugas2.cpp> -<tugas1.cpp> -<tugas3.cpp> -<tugas4.cpp>

[env:tugas3]
build_src_filter = +<tugas3.cpp> -<tugas1.cpp> -<tugas2.cpp> -<tugas4.cpp>

[env:tugas4]
build_src_filter = +<tugas4.cpp> -<tugas1.cpp> -<tugas2.cpp> -<tugas3.cpp>